name = "soopy-mc2025"
author = "soopyc <minecraft@soopy.moe>"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "611de2dc2aedc0173d73fb632202bb4e584871c3470230b9acdec69b86f065fe"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
