name = "soopy-mc2025"
author = "soopyc <minecraft@soopy.moe>"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8d327dff6bf2cf87eb7b3248ae5a1fb5de9ba7729a561fc946bc4713adca5cc"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"

[options]
datapack-folder = "./resources/datapack"
