name = "soopy-mc2025"
author = "soopyc <minecraft@soopy.moe>"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7bc168525114183fe30a298d06a21cab5153a468457e4d62998b1dc769d629d0"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"

[options]
datapack-folder = "./resources/datapack"
