name = "soopy-mc2025"
author = "soopyc <minecraft@soopy.moe>"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2c7374735dd57c746d3230758c54b397012502bf5c515b731f3ef3a3ec0019a"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"

[options]
datapack-folder = "./resources/datapack"
