name = "soopy-mc2026-experimental"
author = "soopyc <minecraft@soopy.moe>"
version = "0.1.0-alpha.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc6e4a060be29c726ca3828d56606e48a6d246258f1dbd1a3bde2a19cc4fbbb7"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
datapack-folder = "./resources/datapack"
