name = "soopy-mc2025"
author = "soopyc <minecraft@soopy.moe>"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33b577d778ebd665964a6f078449ac411186760e558f65bee8f6056816691ab0"

[versions]
fabric = "0.17.3"
minecraft = "1.21.9"

[options]
datapack-folder = "./resources/datapack"
