name = "soopy-mc2025"
author = "soopyc <minecraft@soopy.moe>"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23eea74e6ca84b28adaa8da7445c0a86a8f5163e4e4ed8aad2d15f9d18ddcdd7"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"

[options]
datapack-folder = "./resources/datapack"
