name = "soopy-mc2025"
author = "soopyc <minecraft@soopy.moe>"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eaddbd674041683f5ae05ece389755370f2e035440016d80527e2293ba62e40d"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"

[options]
datapack-folder = "./resources/datapack"
