name = "soopy-mc2026-experimental"
author = "soopyc <minecraft@soopy.moe>"
version = "0.1.0-alpha.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b337c8c1d39fc2beae38d8538927de2cbc74116e305fc41d9fde1b4355d6ea8e"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
datapack-folder = "./resources/datapack"
