name = "soopy-mc2026-experimental"
author = "soopyc <minecraft@soopy.moe>"
version = "0.1.0-alpha.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7b056a5aa407de1d637943b13719365798ccfe6ac44fc1b5c50c4045c5f51ac"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
datapack-folder = "./resources/datapack"
