build:
	pakku export

version:
	@jq .version pakku.json

bump version:
	pakku cfg --version={{version}}
	-git commit pakku.json -m 'aaaaaaaa: bump version to {{version}}'
	just build

clean:
	rm -fr build
