name = "aaaaaaaa"
author = "soopyc"
version = "0.2.5-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46bea31146b95cbff2cb0f42658fd66ce59248ea0285de2be23b6400f036b6ed"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
