name = "aaaaaaaa"
author = "soopyc"
version = "0.2.7-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "735424ec8b255dfaf58f9ad894cce5ffd1a8252086c17b77f9d6260ac55d38a2"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
