[categories]
automation = true
building = true
management = false
tools = true
tweaks = true
world = true
mobs = true
client = true
experimental = false
oddities = false

[automation.feeding_trough]
#How long, in game ticks, between animals being able to eat from the trough
#Allowed values: [1,)
Cooldown = 30
#The maximum amount of animals allowed around the trough's range for an animal to enter love mode
"Max Animals" = 64
#The chance (between 0 and 1) for an animal to enter love mode when eating from the trough
#Allowed values: (0,1]
"Love Chance" = 0.5
Range = 5.0
#Chance that an animal decides to look for a through. Closer it is to 1 the more performance it will take. Decreasing will make animals take longer to find one
"Look Chance" = 0.015
